export const APP_VERSION = "v0.12";
export const GRID_PAGE_SIZE = 8;
export const LIST_PAGE_SIZE = 12;
export const PAGE_SIZE = LIST_PAGE_SIZE;
export const VIEW_MODE_KEY = "chaos_product_view";
export const SIDEBAR_COLLAPSED_KEY = "chaos_sidebar_collapsed";
export const SHARED_SECTION_COLLAPSED_KEY = "chaos_shared_section_collapsed";
export const MAX_COMPARE_PRODUCTS = GRID_PAGE_SIZE;
export const PRICE_CHECK_COOLDOWN_MS = 5 * 60 * 1000;
